#!/bin/bash

echo " :::===  :::  === :::====  :::====  :::====  :::====  :::= === :::====  :::==== "
echo " :::     :::  === :::  === :::  === :::  === :::  === :::===== :::  === :::  ==="
echo "  =====  ===  === ===  === ===  === =======  ======== ======== ===  === ========"
echo "     === ===  === ===  === ===  === ===      ===  === === ==== ===  === ===  ==="
echo " ======   ======  =======   ======  ===      ===  === ===  === =======  ===  ==="
echo""
echo "This script is designed to run all updates for your machine."
echo "Actions that will be taken are as follows:
Identify users logged in,
Update APT repsitories,
Upgrade APT repositories,
Check other updates,
Fix any broken packages,
Remove excess install files."
echo "You must be an administrator on this machine in order to run these updates"
echo "Identify what users are logged into this machine. Make sure there are no unathorized users.
If any unidentified users are listed, stop this program with  [ctrl] C  and investigate."

sudo who

echo "Beginning the update process"

sudo apt -y update

sudo apt -y upgrade

sudo apt -y dist-upgrade

sudo apt update --fix-missing

sudo dpkg --configure -a

sudo apt install -f

sudo apt autoremove

echo " :::===  :::  === :::====  :::====  :::====  :::====  :::= === :::====  :::==== "
echo " :::     :::  === :::  === :::  === :::  === :::  === :::===== :::  === :::  ==="
echo "  =====  ===  === ===  === ===  === =======  ======== ======== ===  === ========"
echo "     === ===  === ===  === ===  === ===      ===  === === ==== ===  === ===  ==="
echo " ======   ======  =======   ======  ===      ===  === ===  === =======  ===  ==="
echo""

echo "Daily updates complete. Go be AWESOME!!"
